# permissions for end users to edit authorizationbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: registry-auth
    app.kubernetes.io/managed-by: kustomize
  name: authorizationbinding-editor-role
rules:
- apiGroups:
  - registry.xuyunjin.top
  resources:
  - authorizationbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.xuyunjin.top
  resources:
  - authorizationbindings/status
  verbs:
  - get
